# Generated by Django 3.2.7 on 2023-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_ordinarymails_reg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinarymails',
            name='abon_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
